name: 'actions-easyconnect'
description: 'run your scripts in easyconnect!'

inputs:
  CLI_OPTS:
    description: "format: '-d {vpnUrl} -u {username} -p {password}'"
    required: true
  SCRIPT:
    description: "your script"
    required: false
  SLEEP_AFTER_LOGIN:
    description: "How many seconds to sleep after login"
    required: false
    default: 5

runs: 
  using: 'composite'
  steps:
    - id: install-easyconnect
      run: sudo bash ${{ github.action_path }}/prerequisite.sh
      shell: bash
    - id: start-easyconnect
      run: |
        bash ${{ github.action_path }}/start.sh &
        sleep ${{ inputs.SLEEP_AFTER_LOGIN }}
      shell: bash
      env: 
        CLI_OPTS:  ${{ inputs.CLI_OPTS }}
    - id: run-user-code
      run: ${{ inputs.SCRIPT }}
      shell: bash
    - id: stop-easyconnect
      run: bash ${{ github.action_path }}/stop.sh
      shell: bash